# This is the first real CI workflow in the course.
# It verifies a change by running tests on a fresh runner.
name: 02 CI Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

env:
  IMAGE_NAME: github-actions

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v

  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEYID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    
      - name: Build Docker image
        run: |
          docker build \
            -t "${IMAGE_NAME}:latest" \
            .

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Tag image for ECR
        run: |
          docker tag \
            "${IMAGE_NAME}:latest" \
            "${{ secrets.ECR_REGISTRY }}/${IMAGE_NAME}:latest"

      - name: Push image to ECR
        run: |
          docker push "${{ secrets.ECR_REGISTRY }}/${IMAGE_NAME}:latest"

      - name: sleep for some time
        run: sleep 60